### ISSUE TITLE
Lotus: Retrieve the CID availability

### ISSUE THREAD

**Issue by brunolm** [mgoelzer/proxy-retrieval#16]
# What

A [lotus.ts](https://github.com/mgoelzer/proxy-retrieval/blob/master/src/services/lotus.ts#L94) function to tell if the CID is available or not and it should include the price & wallet if available

https://github.com/mgoelzer/proxy-retrieval/blob/master/src/services/send-cid-availability.ts#L11

# Why

We need to tell the client if the CID is available or not when we get a `query_cid` message

### Message spec  (out of the scope of this issue)

If Cid is available:

```json
{
  "message": "cid_availability",
  "cid": "0kpacsqedllg0kpacsqedllg0kpacsqedllg0kpacsqedllg",
  "client_token": "03y7ypj6wbit03y7ypj6wbit03y7ypj6wbit=",
  "available": true,
  "price_attofil": "1000000",
  "payment_wallet": "0kyjuke3jbio0kyjuke3jbio"
}
```

If Cid is unavailable:

```json
{
  "message": "cid_availability",
  "cid": "0kpacsqedllg0kpacsqedllg0kpacsqedllg0kpacsqedllg",
  "available": false
}
```

**Comment by brunolm** [comment]
Questions:

The `getClientMinerQueryOffer` function returns:

```js
// success
{
  jsonrpc: '2.0',
  result: {
    Err: '',
    Root: {
      '/': 'baf[...]qmq'
    },
    Piece: null,
    Size: 4096,
    MinPrice: '8192',  // price_attofil ?
    UnsealPrice: '0',  // do we have to consider this?
    PaymentInterval: 1048576,
    PaymentIntervalIncrease: 1048576,
    Miner: 'f03[...]',
    MinerPeer: {
      Address: 'f03[...]',
      ID: '12D[...]2NL',
      PieceCID: null
    }
  },
  id: 0
}

// error (invalid CID)
{
  jsonrpc: '2.0',
  result: {
    Err: 'retrieval query offer errored: get cid info: No state for /bag[...]uhy: datastore: key not found',
    Root: {
      '/': 'bag[...]uhy'
    },
    Piece: null,
    Size: 0,
    MinPrice: '0',
    UnsealPrice: '0',
    PaymentInterval: 1048576,
    PaymentIntervalIncrease: 1048576,
    Miner: 'f03[...]',
    MinerPeer: {
      Address: 'f03[...]',
      ID: '12D[...]2NL',
      PieceCID: null
    }
  },
  id: 0
}
```

- Does it mean that available = `Err == ''` and not available = `Err != ''`?
- `price_attofil` = `MinPrice`?
- `UnsealPrice` used for anything?

Also, how can we get `payment_wallet`? Would this be in another issue or is it related to this API call?

**Comment by mgoelzer** [comment]
>Also, how can we get payment_wallet? Would this be in another issue or is it related to this API call?

I think @aistoc is already working on this logic - correct @aistoc?  Or were you talking about something different?

Answering the question:

Payment wallet needs to be generated in the Nodejs code running on the Retrieval Proxy server.  The API call to use is `Filecoin.WalletNew`.  Generate a Secp256k1 wallet (not a BLS wallet).  The returned address of a Secp wallet should start with `f1...`. (BLS wallets start with `f3...`.)

You need to save both the wallet public key and the wallet private key to the database.

We'll use the funds in the generated Secp wallet to fund the retrieval.  Any left over balance should be deposited to **`f17jk334rev7w6qq74lfujsgvoedmionhggozd22a`**, which will be donated back to the Filecoin Project to help defray the costs of AWS hosting.

**Comment by mgoelzer** [comment]
>    MinPrice: '8192',  // price_attofil ?
>    UnsealPrice: '0',  // do we have to consider this?

I believe that the sum of `MinPrice` and `UnsealPrice` is the total price we want. Let's ask on the Slack channel to be sure, though.

> Does it mean that available = Err == '' and not available = Err != ''?

I think this is right, yes.
